name: gsg-project-group-1

services:
  mysql_db:
    image: mariadb:11
    container_name: mysql_db
    environment:
      MARIADB_ROOT_PASSWORD: "MySQL@123456"
      MARIADB_DATABASE: "pharmacy_delivery_dev"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-pMySQL@123456"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mysql_data:
