services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "MySQL@123456"
      MYSQL_DATABASE: "pharmacy_delivery_dev"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pMySQL@123456"]
      interval: 5s
      timeout: 3s
      retries: 30

  nestjs_api:
    build: .
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
